### ISSUE TITLE
Set Controller endpoint has no response data

### ISSUE THREAD

**Issue by paulmolluzzo** [paulmolluzzo/hydrawise-api#1]
The Hydrawise documentation says that providing the following params will return a response with a `message` of `OK`:

`api_key`: API key for your account
`controller_id`: Unique controller ID
`json`: Must be ‘true’

Following the docs I get a `500 Internal Server Error`. If I change the params to use `controllerid` (notice no `_`) I get a `200 OK` response, but still no json message. If I break the params (a bad API key or something), I get a json body in response with appropriate looking messages.

**Comment by Rexabit** [comment]
I contacted Hydrawise about this but they were unable to help me. I tried a lower value controller_id (1 through 15) and I actually get back the following:

`{"error_msg":"unauthorised"}`

I'm concerned that the endpoint is broken. Have you got this to set the controller?

**Comment by paulmolluzzo** [comment]
> I contacted Hydrawise about this but they were unable to help me. I tried a lower value controller_id (1 through 15) and I actually get back the following:
> 
> {"error_msg":"unauthorised"}

Your controller IDs are `1-15`? The controller I have is a 5 digit number. The `error_msg` you're getting is probably because you're using the wrong ID and that is assigned to someone else.

> I'm concerned that the endpoint is actually broken. Have you got this to actually set the controller?

I honestly have no idea if I am actually getting this to work. I only have one controller to work with, so I can't be certain that it was really set and that's why future commands are working, or if it's defaulting to the only one I have, or it's sending a message to message to run all zones on all controllers.

My overall confidence in their API is limited, and my contact with their support wasn't too fruitful either.

---

How many controllers do you have? If you just have the one then maybe you can proceed without this step (or just accepting anything other than a blatant error). I can tell you that when I run the test suite with my real API key all my sprinklers turn on. 😄  Unfortunately I can't run a test right now because my system is dormant. And it's snowing here!!! 😢

**Comment by Rexabit** [comment]
My controller ID's are 5 digits as well. I tried ID 1 to see if I could get an error back and sure enough I did. I actually added a second controller just without a serial number for testing and I can't get the API to ever switch to it. I contacted Cameron Ryan from the documentation through LinkedIn so maybe I can get some traction on this.

**Comment by paulmolluzzo** [comment]
@rjbouch Also, much ❤️  for finding, trying, and commenting on this repo.

**Comment by paulmolluzzo** [comment]
> My controller ID's are 5 digits as well. I tried ID 1 to see if I could get an error back and sure enough I did.

Ah, OK, good thinking.

> I actually added a second controller just without a serial number for testing and I can't get the API to ever switch to it.

I wonder if it's because there's no serial number?

> I contacted Cameron Ryan from the documentation through LinkedIn so maybe I can get some traction on this.

I also emailed him directly last year and it took a little while to get a response. After looking it over it was about this endpoint, so I'll paste the relevant bits below. Last year they were acquired by a company called Hunter, so I'm not sure if that affected customer service or development operations.

**From me:**
> When I try to use the setcontroller.php endpoint I don't get any data response at all. All I get is a `200 OK`. Is that a bug? Is that because I only have a single controller on my account? The documentation says I should get back a message with `OK` but I don't see that.
> 
> Or perhaps the documentation is out of date. The PDF I was sent looks to be from August, 2014. If there's new documentation that would be awesome to see!

**From Cameron:**
> There is no updated documentation.
> 
> I just checked the code. If you used ‘json’ in the HTTPS GET then you should get an OK message. This is probably missing from the documentation.

That's all I have from them though.

**Comment by Rexabit** [comment]
Hopefully another nudge will get him to look through the code again. I'll let you know if I get any updates.

**Comment by Rexabit** [comment]
Great news! Hydrawise just got back to me, one of the developers confirmed an issue and they're fixing it.

**Comment by paulmolluzzo** [comment]
@rjbouch that is awesome! Thank you for the update! 🙌  If there are changes to make to this package I hope you'll make a PR.

**Comment by RJBoucher** [comment]
More news.

The setcontroller endpoint still has a bug in it, however, it will now give you a proper response. I've also learned that you can provide the 'controller_id' to each endpoint, so if you want to request the schedule for a specific controller you can.

**Comment by paulmolluzzo** [comment]
> I've also learned that you can provide the 'controller_id' to each endpoint, so if you want to request the schedule for a specific controller you can.

That's interesting! You don't need to set the controller in a separate request then, huh? Can you drop an example here or in the README? 🙏

Thanks for the follow up! Now that it's spring maybe I should build something with this... 🤔

**Comment by Rexabit** [comment]
Requesting a schedule for a specific controller:
`GET /api/v1/statusschedule.php?controller_id=[controller_id]&hours=24&api_key=[key] HTTP/1.1`

**Comment by martijndierckx** [comment]
Can you verify if this is still needed in the newer versions of the API endpoints?

**Comment by paulmolluzzo** [comment]
Closing this considering the recent rewrite. If it’s noticed again we can reopen this issue or start a new one.
