### ISSUE TITLE
Problem with local connection

### ISSUE THREAD

**Issue by Bukashk0zzz** [paulmolluzzo/hydrawise-api#7]
Hi,

I have Pro-HC 6 zones. I try to request it from the local network, for example, `curl http://10.0.1.120`, but there are no response look like port 80 closed at all. 

What I am doing wrong? How I can enable local web server on Pro-HC ?
<img width="518" alt="Screenshot 2020-05-14 at 09 16 57" src="https://user-images.githubusercontent.com/1908342/81899510-af464200-95c3-11ea-8512-8adc6c12bc69.png">

**Comment by martijndierckx** [comment]
Can you check if you see the “Local Password” setting on your controller?:
Settings > Config > Local Password

**Comment by Bukashk0zzz** [comment]
There is no button. Something similar to this is only a security code.
But I am not sure.


Main->
![IMG_2404](https://user-images.githubusercontent.com/1908342/81902474-d9e6c980-95c8-11ea-8aa0-382091e562e2.jpeg)


Main->Settings->

![IMG_2405](https://user-images.githubusercontent.com/1908342/81902495-dfdcaa80-95c8-11ea-9210-79a0e3f7b770.jpeg)


Main->Settings->Config->
![IMG_2406](https://user-images.githubusercontent.com/1908342/81902498-e0754100-95c8-11ea-93db-187e1f3b994b.jpeg)

Main->Settings->Config->Security->
![IMG_2407](https://user-images.githubusercontent.com/1908342/81902501-e1a66e00-95c8-11ea-90e5-8ac8badff6f5.jpeg)

Main->Settings->Config->Security->Security Code->
![IMG_2408](https://user-images.githubusercontent.com/1908342/81902504-e23f0480-95c8-11ea-9b46-7ad9ad26cae5.jpeg)

**Comment by martijndierckx** [comment]
Hmmm ... damn.
Seems your FW version doesn't support local communication.
Can you show me the screen where your firmware version is shown? (Please blank out your serial number).

**Comment by Bukashk0zzz** [comment]
FW 4.05

**Comment by jcbigears** [comment]
Hello. Yes I’m also on FW 4.05

**Comment by martijndierckx** [comment]
I've openend a support ticket with Hydrawise.
But if my guess is correct, and the local connection option is not integrated in the newer FW versions, I'm afraid this won't be resolved anytime soon (if ever).

Does the CLOUD connection work for you guys?

**Comment by jcbigears** [comment]
The cloud connection in fact works perfectly well! 
My only observation is that when the zone is actively watering, the image in the Home app changes to look like it's watering, but the word goes from "off" to "idle". Could it be changed to "active" or "on" instead of "off"?

**Comment by martijndierckx** [comment]
That should be the case. But it seems you're running into another issue: https://github.com/martijndierckx/homebridge-hydrawise/issues/12
Can you run the troubleshooting steps as described in that ticket

**Comment by martijndierckx** [comment]
Hydrawise already sent a reply.
Local connection mode is not supported by FW 3 and later.

**Comment by jcbigears** [comment]
Disappointing but at least now we have an answer!
John


On 14 May 2020, at 18:39, martijndierckx <notifications@github.com> wrote:

﻿

Closed #7 <https://github.com/paulmolluzzo/hydrawise-api/issues/7>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/paulmolluzzo/hydrawise-api/issues/7#event-3335492651>,
or unsubscribe

**Comment by Bukashk0zzz** [comment]
@martijndierckx Thank you for investigation
